name: Deep Learning for Question Answering
description: Automated question answering applications using Transformer neural networks
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-04-04"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_dependencies
    script: cml/install_dependencies.py
    arguments: None
    short_summary: Create job to install dependencies.
    cpu: 1
    memory: 8
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_dependencies
    short_summary: Running install dependencies job. 

  - type: create_job
    name: Download Data and Models
    entity_label: download_data_and_models
    script: cml/download_data_and_models.py
    arguments: None
    short_summary: Create job to download data and models. 
    long_summary: Create job to download SQUAD2.0 data and 5 pre-trained transformer models required by the Applications. SQUAD2 data is downloaded to the /data/squad subdirectory. Transformer models are cached to a hidden directory and are never accessed directly.  
    cpu: 1
    memory: 8
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: download_data_and_models
    short_summary: Run job to download data and models.  

  - type: start_application
    name: WikiQA
    subdomain: wikiqa
    script: apps/launch_wikiqa.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    cpu: 2
    memory: 8

  - type: start_application
    name: QA Model Explorer
    subdomain: modelexplorer
    script: apps/launch_model_explorer.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    cpu: 1
    memory: 1

  - type: start_application
    name: QA Data Explorer
    subdomain: dataexplorer
    script: apps/launch_data_visualizer.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    cpu: 1
    memory: 1
